# Generated by Django 4.1 on 2022-08-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=390)),
                ('prazo', models.DateTimeField()),
                ('completa', models.BooleanField(default=False)),
            ],
        ),
    ]
